# MNLI

In [1]:
import os
from datasets import load_dataset
import pandas as pd

os.environ["HF_HUB_DISABLE_SYMLINKS_WARNING"] = "1"

ds = load_dataset("SetFit/mnli")

Repo card metadata block was not found. Setting CardData to empty.

In [2]:
# dictionary of dataset
ds

DatasetDict({
    train: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text'],
        num_rows: 392702
    })
    validation: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text'],
        num_rows: 9815
    })
    test: Dataset({
        features: ['text1', 'text2', 'label', 'idx', 'label_text'],
        num_rows: 9796
    })
})

In [7]:
# function for dataFrame to csv
def saveDF(data_frame,data_frame_name):
    
    data_frame.to_csv(data_frame_name + '.csv', index=False)
    return 0

In [9]:
for enum in ds.keys():
    print(enum)
    dt_name = 'df_'+enum
    print(dt_name)
    dt = pd.DataFrame(ds[enum])
    saveDF(dt,dt_name)

train
df_train
validation
df_validation
test
df_test

In [2]:
# loading training, validation and testing dataset

import pandas as pd

#training set
data_frame_train = pd.read_csv('./sampled_training_data_ten_percent.csv')

#validation set
data_frame_validation = pd.read_csv('./sampled_validation_data_ten_percent.csv')
                                    
#testing set                                  
data_frame_test = pd.read_csv('./sampled_testing_data_five_percent.csv')

In [3]:
data_frame_train

,premise,hypothesis,label,idx,label_text
0,"Jon lifted Susan into his arms, his muscles so...",Susan lifted Jon into the air.,2,207880,contradiction
1,and dropping children off at the sitter and pi...,The children are dropped off at the sitter onl...,0,263102,entailment
2,The Honorable Donna E. Shalala The Secretary o...,Donna E. Shalala is an honorable person for th...,1,299610,neutral
3,Scheduling of follow-up visits depends on type...,Most patients have a follow up two weeks after...,1,344508,neutral
4,This effect does not consider the additional j...,This technology is purely for environmental be...,2,128010,contradiction
...,...,...,...,...,...
31411,"Tommy's eyes opened as he read: ""Jane Finn found.",Jane Finn was very important to Tommy.,1,360356,neutral
31412,After a brief stint living in the Palazzo Vecc...,The Medici's official residence used to belong...,0,219442,entailment
31413,Doors of solid silver open onto the multicolor...,The doors contain more ivory than marble.,1,276936,neutral
31414,"You are not ill, I trust?",Do you feel good?,1,25208,neutral
31415,"One bright Robert Colescott, the first Africa...",Colescott was an African-American artists.,0,97399,entailment

In [4]:
data_frame_test

,premise,hypothesis,label,idx,label_text
0,"Jon lifted Susan into his arms, his muscles so...",Susan lifted Jon into the air.,2,207880,contradiction
1,and dropping children off at the sitter and pi...,The children are dropped off at the sitter onl...,0,263102,entailment
2,The Honorable Donna E. Shalala The Secretary o...,Donna E. Shalala is an honorable person for th...,1,299610,neutral
3,Scheduling of follow-up visits depends on type...,Most patients have a follow up two weeks after...,1,344508,neutral
4,This effect does not consider the additional j...,This technology is purely for environmental be...,2,128010,contradiction
...,...,...,...,...,...
15703,5 million for grants to local legal services p...,A large deal of money has been allocated to lo...,0,288859,entailment
15704,But reviewers agree that the recording succeed...,"Bartoli and Hampson save the recording, becaus...",1,376665,neutral
15705,"We know this, because later she asked Dorcas t...",Dorcas did not bring any.,1,287939,neutral
15706,uh again i mean people think it's expensive bu...,It is much more expensive than any New England...,2,185150,contradiction
15707,"A horse-drawn phaeton will take you on a tour,...",The tour does not pass through the city centre...,2,226805,contradiction

In [5]:
data_frame_validation

,premise,hypothesis,label,idx,label_text
0,yeah well losing is i mean i'm i'm originally ...,The St. Louis Cardinals have always won.,2,3344,contradiction
1,Beside the fortress lies an 18th-century carav...,The fortress was built a number of years after...,1,3852,neutral
2,The twenty mastic villages known collectively ...,Mastihohoria is a collection of twenty mastic ...,0,5009,entailment
3,"Jamaican music ska and, especially, reggae has...",Reggae is the most popular music style in Jama...,1,5398,neutral
4,for me now the address is the same you know my...,I am able to receive mail at my workplace.,1,2335,neutral
...,...,...,...,...,...
977,so you know well a lot of the stuff you hear c...,They consider the West African music to be wor...,0,700,entailment
978,i think they prey on people's um inherent poli...,Some people like listening to recorded message...,1,6399,neutral
979,Rehnquist's conferences are no-nonsense.,Rehnquist was a respected justice.,1,6306,neutral
980,"The renowned Theban queen Nefertari, wife of R...",The renowned Theban queen Nefertari has a tomb...,2,2210,contradiction
981,"In the original, Reich is set up by his host a...",John questions Reich in a hostile manner in th...,0,3936,entailment